name: house_of_auctions
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^3.1.1
  hive: ^2.0.4
  injectable: ^1.5.0
  dio: ^4.0.1
  fresh_dio: ^0.3.1
  flutter_i18n: ^0.30.0
  get_it: ^7.2.0
  freezed: ^0.15.1+1
  styled_text: ^3.0.4+1
  logger: ^1.1.0
  json_annotation: ^4.3.0
  package_info_plus: ^1.3.0
  intro_slider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  flutter_native_splash: ^1.3.1
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.1.0
  json_serializable: ^6.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locales/
    - assets/config/
